@proto = {{$dotenv PROTO}}
@host = {{$dotenv HOST}}
@key = {{$dotenv API_KEY}}

### Ping

GET {{proto}}://{{host}}/ping HTTP/1.1

### Ping Prod

GET https://api.vega.com/ping HTTP/1.1

### Ping Demo

GET https://vega-demo-mapi.vega.com/ping


### Ping QA

GET https://vega-qa-mapi.vega.com/ping

### Ping Dev

GET https://vega-dev-mapi.vega.com/ping

### User

GET {{proto}}://{{host}}/dev
Content-Type: application/json
X-API-Key: {{key}}

{
    "input": 777
}


### All cards

GET {{proto}}://{{host}}/v1/promotions/cards?&p=1 HTTP/1.1
X-API-Key: {{key}}

###

### One card

GET {{proto}}://{{host}}/v1/promotions/card/g63uXgLrso HTTP/1.1

###

POST {{proto}}://{{host}}/portal/v1/startup/ HTTP/1.1
Content-Type: application/json
X-API-Key: {{key}}

{
    "installation": "0123456789D",
    "language": "sk",
    "platform": 1
}

### Test

POST {{proto}}://{{host}}/v1/dashboard/clientPayments HTTP/1.1
Content-Type: application/json
X-API-Key: {{key}}
Parse-Token: r:c718b7be58397ea10a4d674637cec0cf

###
